# Export rom name
export VENDOR := XPe
export XPERIENCE_CHANGELOG := true

PRODUCT_VERSION_MAJOR := 11
PRODUCT_VERSION_MINOR := 1
PRODUCT_VERSION_MAINTENANCE := 1
ROM_VERSION_TAG := 25
#XPE_BUILDTYPE := HOMECASE
WITH_XPERIASUPPORT := true
