# Export rom name
export VENDOR := XPe
export XPERIENCE_CHANGELOG := true

PRODUCT_VERSION_MAJOR := 11
PRODUCT_VERSION_MINOR := 1
PRODUCT_VERSION_MAINTENANCE := 2
ROM_VERSION_TAG := 24
XPE_BUILDTYPE := HOMECASE
ifeq ($(XPE_BUILDTYPE), HOMECASE)
WITH_XPERIASUPPORT := false
endif
ifeq ($(XPE_BUILDTYPE), UNOFFICIAL)
WITH_XPERIASUPPORT := false
endif
ifeq ($(XPE_BUILDTYPE), NIGHTLY)
WITH_XPERIASUPPORT := true
endif

