XPERIENCE_CPU_SMALL_CORES ?= 0,1,2,3
XPERIENCE_CPU_BIG_CORES ?= 4,5,6,7
XPERIENCE_CPU_UNLIMIT_UI ?= 0-7
XPERIENCE_CPU_BG ?= 0-2
XPERIENCE_CPU_FG ?= 0-5
XPERIENCE_CPU_LIMIT_BG ?= 0-1
XPERIENCE_CPU_LIMIT_UI ?= 0-4
XPERIENCE_CPU_DISPLAY ?= 4-7
XPERIENCE_CPU_AUDIO ?= 0-3
# boost properties
PRODUCT_SYSTEM_PROPERTIES += \
    persist.sys.xperience_cpu_big=$(XPERIENCE_CPU_BIG_CORES) \
    persist.sys.xperience_cpu_small=$(XPERIENCE_CPU_SMALL_CORES) \
    persist.sys.xperience_cpu_bg=$(XPERIENCE_CPU_BG) \
    persist.sys.xperience_cpu_limit_bg=$(XPERIENCE_CPU_LIMIT_BG) \
    persist.sys.xperience_cpu_fg=$(XPERIENCE_CPU_FG) \
    persist.sys.xperience_cpu_limit_ui=$(XPERIENCE_CPU_LIMIT_UI) \
    persist.sys.xperience_cpu_unlimit_ui=$(XPERIENCE_CPU_UNLIMIT_UI) \
    persist.sys.xperience_cpu_audio=$(XPERIENCE_CPU_AUDIO) \
    persist.sys.xperience_cpu_display=$(XPERIENCE_CPU_DISPLAY) \
