#!/bin/sh

# Exports

./vendor/xperience/tools/colors

export Changelog=Changelog.txt

# Exports
dir=$ANDROID_BUILD_TOP
OUT=$dir/out/target/product

export device=$1

if [ -f $Changelog ];
then
	rm -f $Changelog
fi

touch $Changelog

# Print something to build output
echo ${bldppl}"Generating changelog..."${txtrst}

for i in $(seq 5);
do
export After_Date=`date --date="$i days ago" +%F`
k=$(expr $i - 1)
	export Until_Date=`date --date="$k days ago" +%F`

	# Line with after --- until was too long for a small ListView
	echo '====================' >> $Changelog;
	echo  "     "$Until_Date    >> $Changelog;
	echo '===================='	>> $Changelog;

	# Cycle through every repo to find commits between 2 dates
	#repo forall -pc 'git log --pretty=format:"%h  %s  [%cn]" --decorate --after=$After_Date --until=$Until_Date' >> $Changelog
	repo forall -pc 'git log --after=$After_Date --until=$Until_Date --pretty=tformat:"%h  %s  [%an]" --abbrev-commit --abbrev=7' >> $Changelog
	echo "" >> $Changelog;
    echo "" >> $Changelog;
done

sed -i 's/project/   */g' $Changelog

#cp $Changelog $OUT/
#rm $Changelog
